// <auto-generated />
using System;
using Api.MasterChefe.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.MasterChefe.Repository.Migrations
{
    [DbContext(typeof(MasterChefeContext))]
    [Migration("20221212235022_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.MasterChefe.Domain.Entidades.Ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Receitaid")
                        .HasColumnType("int");

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Receitaid");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Api.MasterChefe.Domain.Entidades.Receita", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modoFazer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Api.MasterChefe.Domain.Entidades.Ingrediente", b =>
                {
                    b.HasOne("Api.MasterChefe.Domain.Entidades.Receita", null)
                        .WithMany("ingredientes")
                        .HasForeignKey("Receitaid");
                });

            modelBuilder.Entity("Api.MasterChefe.Domain.Entidades.Receita", b =>
                {
                    b.Navigation("ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
